# Generated by Django 5.2.1 on 2025-05-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Default description', max_length=320),
            preserve_default=False,
        ),
    ]
